In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
path = 'C:\\Users\\RAUL\\Documents\\'

In [4]:
post_Educ = pd.read_csv(path + 'fiuba_1_postulantes_educacion.csv')
post_GyE = pd.read_csv(path + 'fiuba_2_postulantes_genero_y_edad.csv')
vistas = pd.read_csv(path + 'fiuba_3_vistas.csv')
postulaciones = pd.read_csv(path + 'fiuba_4_postulaciones.csv')
avisos = pd.read_csv(path + 'fiuba_5_avisos_online.csv')
avisos_Dt = pd.read_csv(path + 'fiuba_6_avisos_detalle.csv')

In [5]:
post_con_aviso = postulaciones.merge(avisos_Dt, on = 'idaviso')

In [6]:
post_con_aviso.head()

,idaviso,idpostulante,fechapostulacion,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1112257047,NM5M,2018-01-15 16:22:34,1,REPRESENTANTES DE ATENCIÓN AL CLIENTE/ RETENCIÓN,"<p><strong><em><span style="""">En </span></em><...",Gran Buenos Aires,NaN,NaN,Part-time,Otro,Atención al Cliente,Eficasia Argentina SA
1,1112257047,1kJqGb,2018-01-15 10:23:11,1,REPRESENTANTES DE ATENCIÓN AL CLIENTE/ RETENCIÓN,"<p><strong><em><span style="""">En </span></em><...",Gran Buenos Aires,NaN,NaN,Part-time,Otro,Atención al Cliente,Eficasia Argentina SA
2,1112257047,eOE9Rr,2018-01-15 10:42:07,1,REPRESENTANTES DE ATENCIÓN AL CLIENTE/ RETENCIÓN,"<p><strong><em><span style="""">En </span></em><...",Gran Buenos Aires,NaN,NaN,Part-time,Otro,Atención al Cliente,Eficasia Argentina SA
3,1112257047,Zrx8Xz,2018-01-30 10:18:14,1,REPRESENTANTES DE ATENCIÓN AL CLIENTE/ RETENCIÓN,"<p><strong><em><span style="""">En </span></em><...",Gran Buenos Aires,NaN,NaN,Part-time,Otro,Atención al Cliente,Eficasia Argentina SA
4,1112257047,ZrKNQY,2018-01-16 17:19:38,1,REPRESENTANTES DE ATENCIÓN AL CLIENTE/ RETENCIÓN,"<p><strong><em><span style="""">En </span></em><...",Gran Buenos Aires,NaN,NaN,Part-time,Otro,Atención al Cliente,Eficasia Argentina SA

In [7]:
areas_distintas_porid = (post_con_aviso.groupby(['idpostulante'])['nombre_area'].agg('nunique')).sort_values(ascending = False)

In [8]:
areas_distintas_porid.head()

idpostulante
axmjOE     140
6rQdqjl    119
8MaQjP3    115
KBzm0ZX    107
jk5aQ1b    105
Name: nombre_area, dtype: int64

In [9]:
areas_distintas_porid = pd.DataFrame(areas_distintas_porid)

In [10]:
areas_distintas_porid = areas_distintas_porid.reset_index()

In [12]:
areas_distintas_porid.head()

  idpostulante  nombre_area
0       axmjOE          140
1      6rQdqjl          119
2      8MaQjP3          115
3      KBzm0ZX          107
4      jk5aQ1b          105

In [19]:
post_Educ['nombre'].value_counts()

Secundario           110256
Universitario        104295
Terciario/Técnico     47733
Otro                  24748
Posgrado               7387
Master                 3598
Doctorado               214
Name: nombre, dtype: int64

In [23]:
post_Educ.groupby(['nombre','estado']).agg('count')

                              idpostulante
nombre            estado
Doctorado         Abandonado            15
                  En Curso              94
                  Graduado             105
Master            Abandonado           144
                  En Curso            1519
                  Graduado            1935
Otro              Abandonado           947
                  En Curso            4919
                  Graduado           18882
Posgrado          Abandonado           317
                  En Curso            2239
                  Graduado            4831
Secundario        Abandonado          3156
                  En Curso            3995
                  Graduado          103105
Terciario/Técnico Abandonado          5692
                  En Curso           15032
                  Graduado           27009
Universitario     Abandonado         14955
                  En Curso           50733
                  Graduado           38607

In [24]:
post_Educ_2 = post_Educ.copy()
aux = pd.DataFrame()

In [35]:
post_Educ_2

       idpostulante             nombre      estado
0              NdJl           Posgrado    En Curso
1              8BkL      Universitario    En Curso
2              1d2B      Universitario    En Curso
3              NPBx      Universitario    En Curso
4              NPBx             Master    En Curso
5              Ym2X               Otro    En Curso
6              ZKl5             Master    En Curso
7             EDD99  Terciario/Técnico    En Curso
8             Y043Z      Universitario    En Curso
9             6M3jr      Universitario    En Curso
10            EpDDJ      Universitario    En Curso
11            abpEZ               Otro    En Curso
12            EZD29      Universitario    En Curso
13            EZD29  Terciario/Técnico    En Curso
14            EZD29               Otro    En Curso
15            YrkoJ             Master    En Curso
16            Z85B5      Universitario    En Curso
17            axaPJ           Posgrado    En Curso
18            1QLLO      Universitario    En Curso
19            Nmkzz  Terciario/Técnico    En Curso
20            6bK4l           Posgrado    En Curso
21            ZvqJ1      Universitario    En Curso
22            eZPbB      Universitario    En Curso
23            aJ5N5           Posgrado    En Curso
24            NOVYV  Terciario/Técnico    En Curso
25            Z48mz           Posgrado    En Curso
26            6JAlR             Master    En Curso
27            ex4j2      Universitario    En Curso
28            6LO1M      Universitario    En Curso
29            5dLpZ      Universitario    En Curso
...             ...                ...         ...
298201      0zPak21      Universitario  Abandonado
298202      wVkMoKL  Terciario/Técnico  Abandonado
298203      RzrQ9Z1         Secundario  Abandonado
298204      0zPakor  Terciario/Técnico  Abandonado
298205      QNrBE5q         Secundario  Abandonado
298206      96XvzB8         Secundario  Abandonado
298207      8MPo2zx      Universitario  Abandonado
298208      X95JkmK      Universitario  Abandonado
298209      1QPMkMO         Secundario  Abandonado
298210      lDLjLG6      Universitario  Abandonado
298211      LNKpKjQ         Secundario  Abandonado
298212      GNZqZmv         Secundario  Abandonado
298213      zvabaB5         Secundario  Abandonado
298214      DrXeX4K      Universitario  Abandonado
298215      ow2p24L  Terciario/Técnico  Abandonado
298216      A3X4Xxm      Universitario  Abandonado
298217      KBr2rGY      Universitario  Abandonado
298218      ow2p214      Universitario  Abandonado
298219      LNKpKvb               Otro  Abandonado
298220      Nzr1r1x         Secundario  Abandonado
298221      wVkMkQm         Secundario  Abandonado
298222      bOjXw0V      Universitario  Abandonado
298223      GNZqAJ9      Universitario  Abandonado
298224      8MPoxaD         Secundario  Abandonado
298225      JBrNMZ3      Universitario  Abandonado
298226      GNZqARp  Terciario/Técnico  Abandonado
298227      ow2p8vk      Universitario  Abandonado
298228      6rPEvwv      Universitario  Abandonado
298229      vVja45X      Universitario  Abandonado
298230      1QPMbX3      Universitario  Abandonado

[298231 rows x 3 columns]

ValueError: labels ['idpostulante' 'nombre' 'estado'] not contained in axis

In [43]:
aux

       idpostulante     nombre    estado
2063         ZaNjjV  Doctorado  Graduado
7063         exdbAj  Doctorado  Graduado
9785         1dpk0O  Doctorado  Graduado
10164        YAXEWq  Doctorado  Graduado
10465        1kWKXz  Doctorado  Graduado
13170        Ee562b  Doctorado  Graduado
13185        Ee40Qz  Doctorado  Graduado
14124        Zr5161  Doctorado  Graduado
17090        YRNOmZ  Doctorado  Graduado
17376        ZWxbkV  Doctorado  Graduado
19096        ERG81N  Doctorado  Graduado
21280        1eWdwB  Doctorado  Graduado
22654        YkN01Z  Doctorado  Graduado
25290        ZxaYa1  Doctorado  Graduado
25594        NqrwvD  Doctorado  Graduado
27245        ZZrmqV  Doctorado  Graduado
28992        a0XaWD  Doctorado  Graduado
30773        ZBe6DR  Doctorado  Graduado
34057        eLdOk9  Doctorado  Graduado
37283        aE1GxW  Doctorado  Graduado
41342        NB56lB  Doctorado  Graduado
42146        8YPD3j  Doctorado  Graduado
42612        5G1krk  Doctorado  Graduado
42791        NYLpJ4  Doctorado  Graduado
45459        5K9ZOq  Doctorado  Graduado
49111        16weJ3  Doctorado  Graduado
49145        69kvMl  Doctorado  Graduado
50701        8Ab6xz  Doctorado  Graduado
54046        6wxP1v  Doctorado  Graduado
54564        ZprBAP  Doctorado  Graduado
...             ...        ...       ...
229178      ZDPA5eb  Doctorado  Graduado
229427      8M2dPbR  Doctorado  Graduado
232479      wVoQQ3e  Doctorado  Graduado
237382      2zPmjAa  Doctorado  Graduado
241987      ow2kvVe  Doctorado  Graduado
243615      2zPQAQ6  Doctorado  Graduado
245475      6rPZp23  Doctorado  Graduado
245931      bOjVl44  Doctorado  Graduado
250227      VNrqNlm  Doctorado  Graduado
252355      96Xjdwv  Doctorado  Graduado
253103      JBrqbdO  Doctorado  Graduado
257520      PmGXvB0  Doctorado  Graduado
262452      pzdKbQM  Doctorado  Graduado
262511      KBrGDGX  Doctorado  Graduado
264212      pzdK6zW  Doctorado  Graduado
264225      ekOQP9p  Doctorado  Graduado
265852      0zPOex9  Doctorado  Graduado
269209      MVrYVwv  Doctorado  Graduado
269348      bOjYlDd  Doctorado  Graduado
270570      MVrvNZN  Doctorado  Graduado
274553      akjaDR9  Doctorado  Graduado
275562      ow2VeXZ  Doctorado  Graduado
280179      2zP0Bq6  Doctorado  Graduado
280351      vVjvrY1  Doctorado  Graduado
280832      bOjd03q  Doctorado  Graduado
288627      bOj3Mjd  Doctorado  Graduado
290611      Yj52vXZ  Doctorado  Graduado
293172      vVjdRZ1  Doctorado  Graduado
294073      QNrz2G2  Doctorado  Graduado
294891      LNKVpYr  Doctorado  Graduado

[105 rows x 3 columns]

In [15]:
post_univ = post_Educ[(post_Educ['nombre'] == 'Universitario') & (post_Educ['estado'] == 'Graduado')].sort_values('idpostulante')
post_sec

In [16]:
post_univ

       idpostulante         nombre    estado
113547      0zB0NWY  Universitario  Graduado
121244      0zB10m8  Universitario  Graduado
121371      0zB11wr  Universitario  Graduado
121632      0zB1J2E  Universitario  Graduado
121350      0zB1oA1  Universitario  Graduado
131085      0zB3Nz9  Universitario  Graduado
131365      0zB3x5M  Universitario  Graduado
105089      0zB4Rrd  Universitario  Graduado
105209      0zB4bv1  Universitario  Graduado
105275      0zB4jvq  Universitario  Graduado
111509      0zB56PM  Universitario  Graduado
111563      0zB5M9v  Universitario  Graduado
122582      0zB6Kxd  Universitario  Graduado
122274      0zB6NMM  Universitario  Graduado
122301      0zB6qGa  Universitario  Graduado
137156      0zB88V8  Universitario  Graduado
136744      0zB8B2r  Universitario  Graduado
130675      0zBAEM8  Universitario  Graduado
130646      0zBAPdv  Universitario  Graduado
130908      0zBAXA9  Universitario  Graduado
130629      0zBAkLM  Universitario  Graduado
130938      0zBAvK1  Universitario  Graduado
132369      0zBDjRr  Universitario  Graduado
132018      0zBDwNM  Universitario  Graduado
114042      0zBEL2v  Universitario  Graduado
114254      0zBEM48  Universitario  Graduado
114340      0zBEVQE  Universitario  Graduado
125986      0zBGp8d  Universitario  Graduado
136616      0zBJa0E  Universitario  Graduado
136249      0zBJr38  Universitario  Graduado
...             ...            ...       ...
198994      zvxYajb  Universitario  Graduado
217933      zvxZJ55  Universitario  Graduado
217811      zvxZZk6  Universitario  Graduado
217741      zvxZzR5  Universitario  Graduado
206483      zvxad2k  Universitario  Graduado
208282      zvxazOD  Universitario  Graduado
224803      zvxbemb  Universitario  Graduado
224419      zvxbvGE  Universitario  Graduado
224394      zvxbvO5  Universitario  Graduado
223214      zvxe6Z6  Universitario  Graduado
223685      zvxekVJ  Universitario  Graduado
219607      zvxjBbJ  Universitario  Graduado
219502      zvxjOom  Universitario  Graduado
219528      zvxjPWE  Universitario  Graduado
214135      zvxlDK5  Universitario  Graduado
214122      zvxljQm  Universitario  Graduado
209026      zvxma83  Universitario  Graduado
229670      zvxoVR3  Universitario  Graduado
231322      zvxok4J  Universitario  Graduado
208494      zvxpde8  Universitario  Graduado
228008      zvxq2oE  Universitario  Graduado
228011      zvxq2rJ  Universitario  Graduado
228323      zvxqWAK  Universitario  Graduado
228100      zvxqpME  Universitario  Graduado
232142      zvxr0P3  Universitario  Graduado
232201      zvxrQbb  Universitario  Graduado
232335      zvxrjBK  Universitario  Graduado
205533      zvxwAlJ  Universitario  Graduado
213712      zvxzJr3  Universitario  Graduado
213760      zvxzrWm  Universitario  Graduado

[38607 rows x 3 columns]

In [47]:
cant_busq_educ = post_Educ.merge(areas_distintas_porid, on = 'idpostulante')
cant_busq_educ.columns = ['idpostulante', 'educacion', 'estado', 'cantidaddeareas']

In [48]:
cant_busq_educ

       idpostulante          educacion      estado  cantidaddeareas
0              NdJl           Posgrado    En Curso                8
1              NdJl      Universitario    Graduado                8
2              8BkL      Universitario    En Curso                6
3              8BkL      Universitario    Graduado                6
4              8BkL           Posgrado    Graduado                6
5              8BkL             Master    Graduado                6
6              1d2B      Universitario    En Curso                3
7              NPBx      Universitario    En Curso                7
8              NPBx             Master    En Curso                7
9              NPBx      Universitario    Graduado                7
10             Ym2X               Otro    En Curso                6
11             Ym2X      Universitario    Graduado                6
12             ZKl5             Master    En Curso                2
13             ZKl5      Universitario    Graduado                2
14            EDD99  Terciario/Técnico    En Curso               11
15            EDD99      Universitario    Graduado               11
16            Y043Z      Universitario    En Curso                1
17            Y043Z  Terciario/Técnico    Graduado                1
18            6M3jr      Universitario    En Curso                1
19            EpDDJ      Universitario    En Curso                2
20            abpEZ               Otro    En Curso                2
21            abpEZ      Universitario    Graduado                2
22            EZD29      Universitario    En Curso               10
23            EZD29  Terciario/Técnico    En Curso               10
24            EZD29               Otro    En Curso               10
25            EZD29  Terciario/Técnico    Graduado               10
26            EZD29      Universitario    Graduado               10
27            EZD29           Posgrado    Graduado               10
28            EZD29               Otro    Graduado               10
29            EZD29      Universitario  Abandonado               10
...             ...                ...         ...              ...
295259      Nzr1lDl      Universitario  Abandonado                1
295260      8MPoLQM         Secundario  Abandonado                2
295261      LNKp4Lq         Secundario  Abandonado                2
295262      dYj4zPY      Universitario  Abandonado                4
295263      Nzr1PdD               Otro  Abandonado                5
295264      PmGPLJZ         Secundario  Abandonado                3
295265      rmdl2Z6      Universitario  Abandonado                4
295266      6rPEZY4      Universitario  Abandonado                1
295267      OqrlPoW      Universitario  Abandonado                4
295268      RzrQPb1         Secundario  Abandonado                4
295269      xkd6aEa      Universitario  Abandonado                3
295270      zvabx6m  Terciario/Técnico  Abandonado                1
295271      4rPbNNE         Secundario  Abandonado                1
295272      0zPak21      Universitario  Abandonado                1
295273      wVkMoKL  Terciario/Técnico  Abandonado                9
295274      RzrQ9Z1         Secundario  Abandonado                7
295275      0zPakor  Terciario/Técnico  Abandonado                4
295276      96XvzB8         Secundario  Abandonado                3
295277      1QPMkMO         Secundario  Abandonado                5
295278      LNKpKjQ         Secundario  Abandonado                1
295279      GNZqZmv         Secundario  Abandonado                8
295280      zvabaB5         Secundario  Abandonado                1
295281      ow2p24L  Terciario/Técnico  Abandonado                1
295282      LNKpKvb               Otro  Abandonado                4
295283      Nzr1r1x         Secundario  Abandonado                3
295284      wVkMkQm         Secundario  Abandonado                2
295285      8MPoxaD         Secundario  Abandonado                1
295286      JBrNMZ3      Universitario  Abandonado                2
295287      GNZqARp  Terciario/Técnico  Abandonado                4
295288      1QPMbX3      Universitario  Abandonado                7

[295289 rows x 4 columns]